apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-server
  namespace: hazelcast
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hazelcast-server
  template:
    metadata:
      labels:
        app: hazelcast-server
    spec:
      serviceAccount: hazelcast
      containers:
      - name: app
        image: ghcr.io/csonp/hazelcast-app:latest
        env:
        # Are we in Kubernetes
        - name: K8S
          value: "true"
        ports:
        - name: http
          containerPort: 8080
        - name: hazelcast
          containerPort: 5701
        # Url to check the container is up
        readinessProbe:
          httpGet:
            path: /k8s
            port: http
          initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-server
  namespace: hazelcast
spec:
  type: NodePort
  selector:
    app: hazelcast-server
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: hazelcast
    port: 5701
    targetPort: hazelcast
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: hazelcast
  namespace: hazelcast
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
  namespace: hazelcast
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  creationTimestamp: null
  name: pod-readers
  namespace: hazelcast
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: hazelcast
  namespace: hazelcast
