---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hazelcast-config
  namespace: hazelcast
data:
  hazelcast.yaml: |
    hazelcast:
      cluster-name: k8s
      network:
        port:
          port: 5701
        join:
          kubernetes:
            enabled: true
            service-name: hazelcast-server
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: hazelcast
  namespace: hazelcast
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
  namespace: hazelcast
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  creationTimestamp: null
  name: pod-readers
  namespace: hazelcast
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: hazelcast
  namespace: hazelcast
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hazelcast-server
  namespace: hazelcast
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hazelcast-server
  template:
    metadata:
      labels:
        app: hazelcast-server
    spec:
      serviceAccount: hazelcast
      containers:
      - name: app
        image: ghcr.io/csonp/hazelcast-app:latest
        env:
        - name: JAVA_OPTS
          value: "-Dhazelcast.config=/config/hazelcast.yaml"
        ports:
        - name: http
          containerPort: 8080
        - name: hazelcast
          containerPort: 5701
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: hazelcast-config
---
kind: Service
apiVersion: v1
metadata:
  name: hazelcast-server
  namespace: hazelcast
spec:
  type: ClusterIP
  selector:
    app: hazelcast-server
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: hazelcast
    port: 5701
    targetPort: hazelcast
---
